import { Property } from '../../utils/Property.js';
import { FluffBase } from '../FluffBase.js';
import { FluffElement } from '../FluffElementImpl.js';
import { MarkerManager } from '../MarkerManager.js';

export interface TestInterpolationPipeComponentInstance extends FluffElement
{
    message: string;
    __message: Property<string>;
}

export type TestInterpolationPipeComponentConstructor = new () => TestInterpolationPipeComponentInstance;

export function createTestInterpolationPipeComponent(): TestInterpolationPipeComponentConstructor
{
    class TestComponent extends FluffElement
    {
        public __message = new Property<string>({ initialValue: 'hello world', propertyName: 'message' });

        public get message(): string
        {
            return this.__message.getValue() ?? '';
        }

        public set message(val: string)
        {
            this.__message.setValue(val);
        }

        // TEST STUB: In real apps, __pipes is generated by the CLI in CodeGenerator.ts
        public override __pipes: Record<string, (v: unknown, ...args: unknown[]) => unknown> = {
            uppercase: (v: unknown): string => String(v)
                .toUpperCase(),
            truncate: (v: unknown, length: unknown): string =>
            {
                const str = String(v);
                const len = typeof length === 'number' ? length : 10;
                return str.length > len ? str.slice(0, len) + '...' : str;
            }
        };

        protected override __render(): void
        {
            this.__getShadowRoot().innerHTML = '<span><!--fluff:text:0--><!--/fluff:text:0--></span>';
            const si = FluffBase.__s.length;
            FluffBase.__s.push('message', 'uppercase');
            this.__setMarkerConfigs([
                [0, [2, 0, [si], [[si + 1, []]]]]
            ]);
        }

        protected override __setupBindings(): void
        {
            this.__initializeMarkers(MarkerManager);
            super.__setupBindings();
        }
    }

    return TestComponent as TestInterpolationPipeComponentConstructor;
}
